# -*- coding: utf-8 -*-
"""house_prediction multiple_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KD7-jwR2oeixhKfcBG32nLq5vc6P2Pm

This is the backend of the app; it is a multiple linear regression algorithm.

"""
##Flask stuff
import ast
from flask import Flask, request, jsonify

app = Flask(__name__)

## Def functions and vars
def ask_user(question,var):
    while True:
        try:
           print(question, end=" ")
           var =  int(input("? "))
           return var
        except:
           print("Invalid input! Enter a number!!")
           continue

bedroom_count = 0
bathroom_count = 0
living_sqft_space = 0
floors = 0

## Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import threading
import time
import requests
"""## Remove unneccesary data"""

import pandas as pd

df = pd.read_csv('data.csv')
df = df.drop(columns=['sqft_lot'])

df.to_csv('data_fix.csv', index=False)

"""## Importing the dataset"""

dataset = pd.read_csv('data_fix.csv')
X = dataset.iloc[:, 2:6].values
y = dataset.iloc[:, 1].values


"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""## Training the Multiple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

"""
## Get user input and predict
bedroom_count = ask_user("\nHow many bedrooms does your house have", bedroom_count)
bathroom_count = ask_user("\nHow many bathrooms does your house have", bathroom_count)
living_sqft_space = ask_user("\nHow many square feet of living space does your house have", living_sqft_space)
floors = ask_user("\nHow many floors does your house have", floors)

predict_for_user = np.array([[bedroom_count, bathroom_count, living_sqft_space, floors]])
predicted_price = regressor.predict(predict_for_user)
print(f"\nPredicted house value for user: {predicted_price[0]:.2f}")
"""

##API stuff

@app.route('/api/house_predict/<path:url_list>', methods=['GET'])
def calculate_from_url(url_list):
    try:
        parsed_list = ast.literal_eval(url_list)
        
        if not isinstance(parsed_list, list):
            return jsonify({"error": "URL path must contain a valid list format"}), 400
            
        predict_for_user = np.array([parsed_list])
        predicted_price = regressor.predict(predict_for_user)
        
        return jsonify({"result": int(predicted_price)})
        
    except (ValueError, SyntaxError):
        return jsonify({"error": "Invalid list format in URL"}), 400

#Keep awake logic (for render so it doesnt sleep ) the logic isnt really working right now
def keep_alive():
    url = "https://house-predictor-sc83.onrender.com/"

    while True:
        try:
            response = requests.get(url, timeout=5)
            print("pinged url")
        except Exception as e:
            print("Failed to ping")

        time.sleep(5)

import os

if __name__ == '__main__':
    ping_thread = threading.Thread(target=keep_alive, daemon=True)
    ping_thread.start()

    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port, debug=False)
